# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NayaabKhan
subtitle: Thoughts of a frontend developer. Also rants.
email: khannayaab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nayaabkhan is a Team Leader and a Frontend developer at StarOfService.com.
  He writes about React, Redux, Design and DIY.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nayaabkhan.in" # the base hostname & protocol for your site
twitter_username: iamnayaabkhan
github_username:  nayaabkhan
facebook_username: nayaab.in

# Build settings
markdown: kramdown
